CREATE TABLE IF NOT EXISTS UserAccounts (
    Id INTEGER NOT NULL CONSTRAINT PK_UserAccounts PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL,
    Password TEXT NOT NULL,
    Role TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS IX_UserAccounts_Username ON UserAccounts (Username);

CREATE TABLE IF NOT EXISTS RawMaterials (
    Id INTEGER NOT NULL CONSTRAINT PK_RawMaterials PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    StockQty INTEGER NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS IX_RawMaterials_Name ON RawMaterials (Name);

CREATE TABLE IF NOT EXISTS Recipes (
    Id INTEGER NOT NULL CONSTRAINT PK_Recipes PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS IX_Recipes_Name ON Recipes (Name);

CREATE TABLE IF NOT EXISTS RecipeIngredients (
    Id INTEGER NOT NULL CONSTRAINT PK_RecipeIngredients PRIMARY KEY AUTOINCREMENT,
    RecipeId INTEGER NOT NULL,
    MaterialId INTEGER NOT NULL,
    Quantity INTEGER NOT NULL,
    CONSTRAINT FK_RecipeIngredients_Recipes_RecipeId FOREIGN KEY (RecipeId) REFERENCES Recipes (Id) ON DELETE CASCADE,
    CONSTRAINT FK_RecipeIngredients_RawMaterials_MaterialId FOREIGN KEY (MaterialId) REFERENCES RawMaterials (Id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS DailyPlans (
    Id INTEGER NOT NULL CONSTRAINT PK_DailyPlans PRIMARY KEY AUTOINCREMENT,
    RecipeId INTEGER NOT NULL,
    TargetQty INTEGER NOT NULL,
    CONSTRAINT FK_DailyPlans_Recipes_RecipeId FOREIGN KEY (RecipeId) REFERENCES Recipes (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DailyActuals (
    Id INTEGER NOT NULL CONSTRAINT PK_DailyActuals PRIMARY KEY AUTOINCREMENT,
    RecipeId INTEGER NOT NULL,
    ActualQty INTEGER NOT NULL,
    RecordedAt TEXT NOT NULL,
    CONSTRAINT FK_DailyActuals_Recipes_RecipeId FOREIGN KEY (RecipeId) REFERENCES Recipes (Id) ON DELETE CASCADE
);
